export const clasa10ChaptersLessons = [
  [
    "Ce este termodinamica - sistem termodinamic și parametrii de stare",
    "Ecuația de stare a gazului ideal",
    "Transformarea izobară - proprietăți și aplicații",
    "Transformarea izocoră - proprietăți și aplicații",
    "Transformarea izotermă - proprietăți și aplicații",
    "Transformarea adiabată - proprietăți și aplicații",
    "Transformarea politropă - cazul general al transformărilor",
  ],
  [
    "Lucrul mecanic în termodinamică",
    "Energia internă și căldura",
    "Primul principiu al termodinamicii - enunțuri și aplicații",
    "Gradele de libertate ale moleculelor",
    "Căldurile specifice pentru gaze ideale",
    "Aplicații ale primului principiu la transformări",
    "Cicluri termodinamice simple",
  ],
  [
    "Procese reversibile și ireversibile",
    "Entropia și al doilea principiu",
    "Motoare termice - principiul de funcționare",
    "Randamentul motoarelor termice",
    "Ciclul Carnot și randamentul maxim teoretic",
    "Mașini frigorifice și pompe de căldură",
  ],
  [
    "Sarcina electrică și legea conservării sarcinii",
    "Legea lui Coulomb și forța electrostatică",
    "Câmpul electric - intensitatea câmpului electric",
    "Liniile de câmp electric și reprezentarea câmpului",
    "Potențialul electric și diferența de potențial",
    "Legătura între câmpul electric și potențialul electric",
    "Capacitatea electrică și condensatoarele",
  ],
  [
    "Curentul electric - intensitatea curentului",
    "Legea lui Ohm pentru o porțiune de circuit",
    "Rezistența electrică și rezistivitatea",
    "Asocierea rezistoarelor în serie și în paralel",
    "Legea lui Ohm pentru circuitul complet",
    "Lucrul și puterea în curent continuu",
    "Legile lui Kirchhoff și aplicații",
  ],
  [
    "Magnetismul natural și artificial - proprietățile magneților",
    "Câmpul magnetic - inducția magnetică",
    "Forța exercitată de câmpul magnetic asupra unui conductor parcurs de curent",
    "Forța Lorentz - acțiunea câmpului magnetic asupra unei particule încărcate",
    "Câmpul magnetic produs de curenți electrici",
    "Aplicații ale forței magnetice - motorul electric",
    "Inducția electromagnetică - legea lui Faraday",
  ],
];
