export const clasa9ChaptersLessons = [
  [
    "Ce este un punct material și cum descriem mișcarea",
    "Mișcarea rectilinie uniformă – mers constant, fără opriri",
    "Mișcarea cu accelerație – când viteza se schimbă",
    "Graficele mișcării – cum citim poziția, viteza și accelerația",
    "Mișcarea pe verticală – căderea liberă și aruncarea în sus",
    "Legătura dintre poziție, viteză și accelerație",
    "Probleme frecvente și metode de rezolvare",
  ],
  [
    "Ce este forța și cum influențează mișcarea",
    "Tipuri de forțe: gravitațională, elastică, de frecare, etc.",
    "Cum reprezentăm corect toate forțele – diagrama forțelor",
    "Echilibrul forțelor – când totul stă pe loc",
    "Acțiune și reacțiune – legea a III-a a lui Newton",
    "Planul înclinat și alte situații clasice",
    "Probleme combinate – aplicarea legilor lui Newton",
  ],
  [
    "Ce înseamnă ‘lucru mecanic’ și când apare",
    "Puterea și randamentul – cât de eficient lucrăm",
    "Energia cinetică – mișcarea în termeni energetici",
    "Energia potențială – gravitațională și elastică",
    "Teorema variației energiei cinetice",
    "Conservarea energiei mecanice",
    "Exerciții tipice și aplicații utile",
  ],
  [
    "Impulsul mecanic – ce e și cum se calculează",
    "Relația dintre forță și impuls",
    "Legea conservării impulsului",
    "Coliziuni elastice și inelastice – diferențe esențiale",
    "Exemple clasice de ciocniri",
    "Cum comparăm conservarea energiei și a impulsului",
  ],
  [
    "Cum se propagă lumina – raze și umbre",
    "Reflexia luminii și legile reflexiei",
    "Imaginea într-o oglindă plană",
    "Oglinzi sferice – formarea imaginilor",
    "Refracția luminii și legea lui Snell",
    "Lentilele – convergente și divergente",
    "Cum apar imaginile în lentile",
    "Aplicații: ochiul, lupa și alte instrumente optice",
  ],
  [
    "Ce înseamnă ‘echilibru’ în fizică",
    "Condițiile de echilibru pentru un punct material",
    "Momentele de forță și echilibrul la rotire",
    "Levierul, balanța și alte aplicații ale momentului",
    "Presiunea într-un lichid – început de hidrostatică",
    "Legea lui Pascal și aplicațiile ei",
    "Legea lui Arhimede – forța care ține lucrurile la suprafață",
    "Probleme mixte de echilibru și hidrostatică",
  ],
]; 