import {
  Atom,
  Award,
  BookOpen,
  Brain,
  Calculator,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  FlaskConical,
  GraduationCap,
  Lightbulb,
  ListChecks,
  Microscope,
  Orbit,
  Rocket,
  Sigma,
  Star,
  Target,
  Telescope,
  Timer,
  Trophy,
  Zap,
  type LucideIcon,
} from "lucide-react"

export const TEST_ICON_OPTIONS: { id: string; label: string }[] = [
  { id: "ClipboardList", label: "Listă (default)" },
  { id: "ClipboardCheck", label: "Listă bifată" },
  { id: "ListChecks", label: "Bife" },
  { id: "CheckCircle2", label: "Cerc bifat" },
  { id: "Brain", label: "Creier" },
  { id: "Lightbulb", label: "Bec" },
  { id: "Target", label: "Țintă" },
  { id: "Trophy", label: "Trofeu" },
  { id: "Award", label: "Medalie" },
  { id: "Star", label: "Stea" },
  { id: "GraduationCap", label: "Toca" },
  { id: "BookOpen", label: "Carte" },
  { id: "Calculator", label: "Calculator" },
  { id: "Sigma", label: "Sigma" },
  { id: "Atom", label: "Atom" },
  { id: "Orbit", label: "Orbita" },
  { id: "Microscope", label: "Microscop" },
  { id: "FlaskConical", label: "Eprubeta" },
  { id: "Telescope", label: "Telescop" },
  { id: "Rocket", label: "Rachetă" },
  { id: "Zap", label: "Fulger" },
  { id: "Timer", label: "Cronometru" },
]

const ICON_MAP: Record<string, LucideIcon> = {
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  CheckCircle2,
  Brain,
  Lightbulb,
  Target,
  Trophy,
  Award,
  Star,
  GraduationCap,
  BookOpen,
  Calculator,
  Sigma,
  Atom,
  Orbit,
  Microscope,
  FlaskConical,
  Telescope,
  Rocket,
  Zap,
  Timer,
}

export function resolveTestIcon(name: string | null | undefined): LucideIcon | null {
  if (!name) return null
  return ICON_MAP[name] ?? null
}
